server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://mongodb:root@cluster-0.ccexft8.mongodb.net/microservice?retryWrites=true&w=majority

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
